# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Francesca Giannetti
email: fg@francescagiannetti.com
description: >- # this means to ignore newlines until "baseurl:"
  portfolio website for Francesca Giannetti
twitter_username: jo_frankie
github_username: giannetti
minimal_mistakes_skin: dirt
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

collections:
  projects:
    output: true
    permalink: /:collection/:path/

# comments
comments:
  provider: "disqus"
  disqus:
    shortname: "portfolio-84oensokxg"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "Francesca Giannetti"
  avatar : "/assets/images/fg-2022-headshot.jpg"
  bio    : "Digital humanities librarian with interests in romance literatures, music, running, and cats."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:francesca.giannetti@rutgers.edu"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mstdn.social/@jo_frankie"
    - label: " Bluesky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/jofrankie.bsky.social"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giannetti"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square ai-fw"
      url: "https://scholar.google.com/citations?user=G3dOYqcAAAAJ&hl=en"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# attempting to call jQuery before any other javascripts to fix lunr search
footer_scripts:
  - /assets/js/vendor/jquery/jquery-3.6.0.js
